version: "3.8"
services:
  app:
    build: ./app/
    ports:
     - 8081:8081
    networks:
        - course_reg_nw
  coursedb:
    build: ./database/
    networks:
        - course_reg_nw
networks:
   course_reg_nw:
      driver: bridge